import type { Metadata } from "next";
import "./globals.css";
// Import the PageTransition component using relative path
import PageTransition from "../components/PageTransition";

export const metadata: Metadata = {
  title: "Shadows of Void",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        {/* Wrap children with PageTransition */}
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
