import type { Metadata } from "next";
// Remove EB_Garamond import
// import { EB_Garamond } from "next/font/google";
import "./globals.css";

// Remove EB Garamond configuration
// const eb_garamond = EB_Garamond({
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700"], // Example weights
// });

// Remove or comment out Inter if it's not needed
// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Restore original body class */}
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
